services:
  app:
    build: .
    container_name: apidevops_app
    ports:
      - "8000:8000"
    environment:
      - ENV=test
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=apidevops_test
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_test:5432/apidevops_test
    depends_on:
      - db_test

volumes:
  postgres_data_dev:
